### ISSUE TITLE
Location values cannot contain NaNs.

### ISSUE THREAD

**Issue by dieseltravis** [TheCommsChannel/mesh-rangetest-map#4]
I get the following error in the console:
```
> python rtmap.py
Traceback (most recent call last):
  File "D:\Projects\github\mesh-rangetest-map\rtmap.py", line 131, in <module>
    create_map_with_layers(csv_files, output_file)
  File "D:\Projects\github\mesh-rangetest-map\rtmap.py", line 59, in create_map_with_layers
    m = folium.Map(location=initial_map_center, zoom_start=13, tiles="OpenStreetMap", control_scale=True)
  File "D:\Projects\github\mesh-rangetest-map\venv\lib\site-packages\folium\folium.py", line 278, in __init__
    self.location = validate_location(location)
  File "D:\Projects\github\mesh-rangetest-map\venv\lib\site-packages\folium\utilities.py", line 101, in validate_location
    raise ValueError("Location values cannot contain NaNs.")
ValueError: Location values cannot contain NaNs.
```

CSV range test files: 

[thrw-rangetest-2024-11-21.csv](https://github.com/user-attachments/files/17852990/thrw-rangetest-2024-11-21.csv)
[thtd-rangetest-2024-11-21.csv](https://github.com/user-attachments/files/17852991/thtd-rangetest-2024-11-21.csv)

**Comment by itCarl** [comment]
Your GPS/location data is missing.
